### ISSUE TITLE
output redirected to files?

### ISSUE THREAD

**Issue by Elbullazul** [bluedxca93/18-20#1]
just gave it a try, got two output files with a weird name

**Comment by bluedxca93** [comment]
run it in terminal 
./port input.css > output.css .
if sed is installed it should work.
don't know what your two output files are.

**Comment by bluedxca93** [comment]
@Elbullazul please provide an example file so i can take a look at your issue!
what the hell is winoldbasic b.t.w.?

**Comment by Elbullazul** [comment]
I think it's because I didn't pipe the output like you did (forgot the ">" sign)

**Comment by Elbullazul** [comment]
![windows-beta-2](http://www.betaarchive.com/imageupload/1301339986.or.93149.png)

**Comment by cinnamoner** [comment]
@Elbullazul 
I like the look of it. Delightful combination of colors.

**Comment by Elbullazul** [comment]
ok, I had it wrong, it works now
