### ISSUE TITLE
How can i use port?

### ISSUE THREAD

**Issue by raveit65** [bluedxca93/18-20#3]
Can you write a readme how to use it.
I'm currently start with porting Ubuntu-Mate themes so your script would be helpful for the first port.
I tried to execute port in gtk-3.0 folder in a theme, but nothing happens.

**Comment by bluedxca93** [comment]
Hi,
basic usage ./port input.css > output.css

REQUIREMENTS:
sudo spt-get install perl sed 
get it with:

```
 wget https://raw.githubusercontent.com/bluedxca93/18-20/master/port
 chmod a+x port
```

this should create a 3.20 and read css in 3.0 folder move apps/*.css temporaly in the top 3.0 folder
be sure to have rename  and sed installed
`for f in *.css ; do ./port $f > $f-20;done ; mkdir -p 3.20; cp *.css-20 3.20; cd 3.20; rename "s/-20//g" *.css-20; cd ..; rm *.css-20`

**Comment by bluedxca93** [comment]
@raveit65. script now working?
you might take a look at my ambiance version and the one from iain lane on launchpad?

**Comment by raveit65** [comment]
yeap it works, but at least that is only a useful helper for a first syntax port.
Thanks
